### ISSUE TITLE
No Error Message When Putting in Bad Password

### ISSUE THREAD

**Issue by owenkellogg** [anypay/anypayx.com#1]
![IMAGE 2022-03-06 16:48:16](https://user-images.githubusercontent.com/508282/156930602-518ae1cf-5190-4140-9400-6a9973b7add8.jpg)

**Comment by eddiewillers** [comment]
<img width="610" alt="Screenshot 2023-04-19 at 16 11 54" src="https://user-images.githubusercontent.com/4019818/233136190-bd130975-c62e-4391-b146-7ced5cb7f2bc.png">

**Comment by eddiewillers** [comment]
This error message now appears when the user enters the wrong password. It could be capitalized but is better than nothing.
